---
version: '3.4'
services:
  gm:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        GRAFFITI_MONKEY_VERSION: "${SOURCE_BRANCH}"

    command:
      - graffiti-monkey
      - --config=/etc/graffiti-monkey/config.yml
      - --append
      - --dryrun
      - -vvv
    environment:
      AWS_REGION: us-east-1
    volumes:
      - ./conf/example_config.yml:/etc/graffiti-monkey/config.yml
    networks:
      - local

  builder:
    image: ${IMAGE_NAME}:builder
    build:
      context: .
      target: builder
    command:
      - python
      - setup.py
      - test


networks:
  local:
